spring.application.name=Sylphy
telegram.bot.name=SylphyBot
telegram.bot.token=8854762136:AAE4IMZU_ENA0ym74YBo_RV9GcHKPxQNiII
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.base-url=https://api.mistral.ai/v1
#spring.ai.openai.api-key=AIzaSyATUlq7fprYs4Q_LnONREOrP298PWPA3bM
spring.ai.openai.api-key=1d52cIIOTy3jpimtAwPCe9Ww7SJvuqY7
#spring.ai.openai.chat.options.model=gemini-3.5-flash
spring.ai.openai.chat.options.model=mistral-small-latest